apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculation-module
  name: calculation-module
spec:
  replicas: 0
  selector:
    matchLabels:
      app: calculation-module
  strategy: {}
  template:
    metadata:
      labels:
        app: calculation-module
    spec:
      containers:
      - image: hkstwk/calculation-module:v1.3.1
        name: calculation-module
        resources: {}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://calculation-module-mysql:3306/calculation-module-db
          - name: SERVER_PORT
            value: '8080'
