apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculation-module
  name: calculation-module
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32010
  selector:
    app: calculation-module
  type: NodePort
