apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: calculation-module-mysql
  name: calculation-module-mysql
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 32001
  selector:
    app: calculation-module-mysql
  type: NodePort
status:
  loadBalancer: {}
