spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Hibernate settings for MySQL
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cors Configuration
cors.allow-credentials=false
cors.allowed-origins=*
cors.allowed-methods=GET, POST, PUT, DELETE, OPTIONS
cors.allowed-headers=*
cors.max-age=3600