spring.application.name=calculation-module

spring.liquibase.change-log=db/changelog/db.changelog-master.xml

# Database connection details
spring.datasource.url=jdbc:mysql://localhost:3316/calculation-module-db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=test
spring.datasource.password=test

# Hibernate settings for MySQL
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false

# Cors Configuration
cors.allow-credentials=true
cors.allowed-origins=http://localhost:3000,http://localhost:4200
cors.allowed-methods=POST, OPTIONS
cors.allowed-headers=*
cors.max-age=3600

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://hkstwk-dev.eu.auth0.com/

calculation.module.compound.enabled=true
calculation.module.compound.rounding-mode=half_up
calculation.module.currency=EUR

calculation.module.bucket4j.bucket.key="test-bucket"
calculation.module.bucket4j.bucket.capacity=60
calculation.module.bucket4j.bucket.refill-type=INTERVALLY
calculation.module.bucket4j.bucket.refill-amount=30
calculation.module.bucket4j.bucket.refill-interval=PT60S
calculation.module.bucket4j.expiration-after-write=P90D
