name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: "corretto"
          cache: maven

      # Build step
      - name: Build with Maven
        run: mvn -B --update-snapshots clean compile

      # Unit tests step
      - name: Run unit tests
        run: mvn test
        if: success()

      # Integration tests step
      - name: Run integration tests
        run: mvn -B failsafe:integration-test failsafe:verify -f pom.xml
        if: success()

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}