name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      # Build step
      - name: Build with Maven
        run: mvn -B clean compile

      # Unit tests step
      - name: Run unit tests
        run: mvn -B test
        if: success()

      # Integration tests step
      - name: Run integration tests
        run: mvn -B failsafe:integration-test -f pom.xml
        if: success()